# Dummy configuration - to be replaced in production
# for Ellie Lockhart natural language research project

title = "Dummy configuration"

[database]
database_type = "psql"
database_server_address = "localhost"
database_login = "python_access"
database_password = "pyauth"
database_specific_database = "media-viewpoints"

[job]
table_to_process = "reviews_tlou2_no_username_raw"
correct_spelling = 1
ngram_depth = 3
word_freq_1 = "lesbian"
word_freq_2 = "graphics"
word_freq_3 = "agenda"
word_freq_4 = "abby"
word_freq_5 = "ellie"
word_freq_6 = "joel"
word_freq_7 = "lev"
word_freq_8 = "trans"
word_freq_9 = "transgender"
word_freq_10 = "tranny"
word_freq_11 = "sjw"
word_freq_12 = "agenda"
word_freq_13 = "gay"
word_freq_14 = "kill"
word_freq_16 = "hate"
word_freq_17 = "love"
word_freq_18 = "dina"